server:
  port: 9080

spring:
  application:
    name: prepare-data

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7080/eureka/
  instance:
      prefer-ip-address: true

hibernate:
  dialect: org.hibernate.dialect.PostgreSQL9Dialect
  connection:
    driver_class: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Input_Credit_Info
    username: postgres
    password: arsen1995
  default_schema: Borrower
  show_sql: true
  enable_lazy_load_no_trans: true